name: Frontend CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-push-run:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: vishwadeep91/front-end-react-app:${{ github.run_number }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker Image
      run: |
        docker build -t $IMAGE_NAME .

    - name: Run Docker Container
      run: |
        docker run -d -p 8081:80 $IMAGE_NAME
